package com.gasthaus.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Maps to the "reviews" table.
 *
 * Review is now ORDER-LEVEL, not item-level.
 * A customer leaves one review per completed order (covering the whole experience).
 *
 * Key changes from item-level design:
 *   - menuItem is now optional (nullable) — kept for backwards compatibility with
 *     any existing per-item reviews already in the DB, but new reviews omit it.
 *   - Unique constraint changed from (customer_id, menu_item_id, order_id)
 *     to (customer_id, order_id) — one review per customer per order.
 *   - orderId is exposed as a @JsonProperty so clients can display
 *     a consistent order reference without loading the full Order object.
 */
@Entity
@Table(
    name = "reviews",
    uniqueConstraints = {
        /**
         * One review per customer per order.
         * Prisma equivalent: @@unique([customerId, orderId])
         */
        @UniqueConstraint(
            name = "uk_review_customer_order",
            columnNames = {"customer_id", "order_id"}
        )
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(of = "id")
@ToString(exclude = {"customer", "menuItem", "order"})
public class Review {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * Star rating 1–5. Range enforced by Bean Validation in CreateReviewRequest.
     */
    @Column(nullable = false)
    private Integer rating;

    /** Optional review text. */
    @Column(columnDefinition = "text")
    private String comment;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    // ──────────────────────────────────────────────────────────
    // RELATIONSHIPS
    // ──────────────────────────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "customer_id", nullable = false)
    private User customer;

    /**
     * Optional — order-level reviews do not reference a specific menu item.
     * Kept nullable so legacy per-item reviews in the DB remain valid.
     * optional = true and nullable = true generate a nullable FK column.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "menu_item_id", nullable = true)
    private MenuItem menuItem;

    /**
     * @JsonIgnore on the field suppresses the full Order object from serialisation.
     * We expose only the order UUID via getOrderId() below.
     */
    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    /**
     * Exposes the order UUID as "orderId" in JSON without serialising the full
     * Order graph. Clients use this to display a consistent order reference string.
     *
     * Manual getter (not generated by Lombok @Getter) so Jackson picks it up as
     * a separate "orderId" property while getOrder() remains @JsonIgnore'd.
     */
    @JsonProperty("orderId")
    public UUID getOrderId() {
        return order != null ? order.getId() : null;
    }
}
